{
  parserClass="com.oscadplugin.parser.OscadParser"
  stubParserClass="com.oscadplugin.parser.GeneratedParserUtilBase"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Oscad"
  psiImplClassSuffix="Impl"
  psiPackage="com.oscadplugin.psi"
  psiImplPackage="com.oscadplugin.psi.impl"

  elementTypeHolderClass="com.oscadplugin.psi.OscadTypes"
  elementTypeClass="com.oscadplugin.psi.OscadElementType"
  tokenTypeClass="com.oscadplugin.psi.OscadTokenType"
}

simpleFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY