/* The following code was generated by JFlex 1.4.3 on 1-4-13 13:45 */

package com.oscadplugin;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import com.oscadplugin.psi.OscadTypes;
import com.intellij.psi.TokenType;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 1-4-13 13:45 from the specification file
 * <tt>C:/Users/Joost/Dropbox/Projects/Oscad/src/com/oscadplugin/Oscad.flex</tt>
 */
class OscadLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int cond_use = 8;
  public static final int cond_comment = 2;
  public static final int cond_include = 6;
  public static final int YYINITIAL = 0;
  public static final int cond_string = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4, 4
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\2\1\1\1\0\1\5\1\2\22\0\1\4\1\6\1\37"+
    "\1\0\1\35\1\0\1\41\3\0\1\7\1\12\1\0\1\12\1\34"+
    "\1\24\12\10\1\0\1\43\1\23\1\40\1\22\2\0\1\50\3\36"+
    "\1\11\3\36\1\45\2\36\1\51\1\36\1\46\5\36\1\47\4\36"+
    "\1\44\1\36\1\0\1\3\2\0\1\36\1\0\1\33\1\36\1\15"+
    "\1\20\1\21\1\30\2\36\1\13\2\36\1\16\1\26\1\14\1\27"+
    "\2\36\1\32\1\25\1\31\1\17\5\36\1\0\1\42\uff83\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\5\0\1\1\1\0\1\2\4\3\1\0\3\3\2\0"+
    "\1\4\1\5\2\0\1\6\1\3\3\7\1\0\1\10"+
    "\1\7\1\11\2\7\1\12\1\13\1\3\1\2\1\3"+
    "\1\14\3\3\2\15\5\3\1\16\1\0\1\2\2\0"+
    "\11\3\1\2\2\3\1\0\1\17\1\20\3\3\1\21"+
    "\2\3\1\22\2\3\1\23\2\3\1\24\5\3\1\0"+
    "\1\25\1\26\2\3\1\27\1\30";

  private static int [] zzUnpackAction() {
    int [] result = new int[94];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\52\0\124\0\176\0\250\0\322\0\374\0\u0126"+
    "\0\u0150\0\u017a\0\u01a4\0\u01ce\0\u01f8\0\u0222\0\u024c\0\u0276"+
    "\0\u02a0\0\u0150\0\u02ca\0\374\0\u02f4\0\u031e\0\u02ca\0\u0348"+
    "\0\u02ca\0\u0372\0\u039c\0\u03c6\0\u02ca\0\u03f0\0\u02ca\0\u041a"+
    "\0\u0444\0\u02ca\0\u02ca\0\u046e\0\u0498\0\u04c2\0\u0150\0\u04ec"+
    "\0\u0516\0\u0540\0\u02ca\0\u056a\0\u0594\0\u05be\0\u05e8\0\u0612"+
    "\0\u063c\0\u02ca\0\u041a\0\u0666\0\u0690\0\u06ba\0\u06e4\0\u070e"+
    "\0\u0738\0\u0762\0\u078c\0\u07b6\0\u07e0\0\u080a\0\u0834\0\u0690"+
    "\0\u085e\0\u0888\0\u08b2\0\u02ca\0\u0150\0\u08dc\0\u0906\0\u0930"+
    "\0\u0150\0\u095a\0\u0984\0\u0150\0\u09ae\0\u09d8\0\u0150\0\u0a02"+
    "\0\u0a2c\0\u0150\0\u0a56\0\u0a80\0\u0aaa\0\u0ad4\0\u0afe\0\u0b28"+
    "\0\u02ca\0\u0150\0\u0b52\0\u0b7c\0\u02ca\0\u02ca";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[94];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\2\6\1\0\2\6\1\7\1\0\1\10\1\11"+
    "\1\0\1\12\3\11\1\13\1\11\1\14\2\7\1\15"+
    "\1\11\1\16\1\11\1\17\1\20\2\11\1\21\1\22"+
    "\1\11\1\23\1\24\1\25\1\26\1\27\1\30\5\11"+
    "\7\31\1\32\42\31\1\33\1\0\1\33\1\34\33\33"+
    "\1\35\12\33\1\36\2\0\17\36\1\37\1\36\1\40"+
    "\25\36\1\41\2\0\17\41\1\42\27\41\1\0\2\6"+
    "\1\0\2\6\104\0\1\43\21\0\1\10\1\44\1\0"+
    "\6\11\1\44\3\0\7\11\1\45\1\0\1\11\5\0"+
    "\6\11\10\0\2\11\1\0\7\11\3\0\7\11\2\0"+
    "\1\11\5\0\6\11\10\0\2\11\1\0\1\11\1\46"+
    "\5\11\3\0\3\11\1\47\3\11\2\0\1\11\5\0"+
    "\6\11\10\0\2\11\1\0\1\11\1\50\5\11\3\0"+
    "\1\51\6\11\2\0\1\11\5\0\6\11\10\0\2\11"+
    "\1\0\3\11\1\52\3\11\3\0\7\11\2\0\1\11"+
    "\5\0\6\11\7\0\1\53\14\0\1\54\35\0\2\11"+
    "\1\0\7\11\3\0\2\11\1\55\4\11\2\0\1\11"+
    "\5\0\6\11\10\0\2\11\1\0\4\11\1\56\2\11"+
    "\3\0\6\11\1\57\2\0\1\11\5\0\6\11\10\0"+
    "\2\11\1\0\7\11\3\0\5\11\1\60\1\11\2\0"+
    "\1\11\5\0\6\11\10\0\1\45\154\0\1\43\52\0"+
    "\1\43\17\0\2\11\1\0\7\11\3\0\7\11\2\0"+
    "\1\11\5\0\1\61\5\11\24\0\1\62\25\0\1\33"+
    "\1\0\1\33\1\0\33\33\1\0\12\33\3\0\1\31"+
    "\10\0\1\31\14\0\2\31\4\0\1\31\12\0\1\36"+
    "\2\0\17\36\1\0\1\36\1\40\25\36\1\63\2\0"+
    "\17\63\1\0\1\63\1\40\25\63\1\41\2\0\17\41"+
    "\1\0\27\41\10\0\1\64\1\11\1\65\7\11\3\0"+
    "\7\11\2\0\1\11\5\0\6\11\10\0\1\45\1\66"+
    "\7\0\1\66\40\0\2\11\1\0\2\11\1\67\4\11"+
    "\3\0\7\11\2\0\1\11\5\0\6\11\10\0\2\11"+
    "\1\0\5\11\1\70\1\11\3\0\7\11\2\0\1\11"+
    "\5\0\6\11\10\0\2\11\1\0\6\11\1\71\3\0"+
    "\7\11\2\0\1\11\5\0\6\11\10\0\2\11\1\0"+
    "\7\11\3\0\1\72\6\11\2\0\1\11\5\0\6\11"+
    "\1\54\1\53\50\54\10\0\2\11\1\0\5\11\1\73"+
    "\1\11\3\0\7\11\2\0\1\11\5\0\6\11\10\0"+
    "\2\11\1\0\1\11\1\74\5\11\3\0\7\11\2\0"+
    "\1\11\5\0\6\11\10\0\2\11\1\0\3\11\1\75"+
    "\3\11\3\0\7\11\2\0\1\11\5\0\6\11\10\0"+
    "\2\11\1\0\4\11\1\76\2\11\3\0\7\11\2\0"+
    "\1\11\5\0\6\11\10\0\2\11\1\0\7\11\3\0"+
    "\7\11\2\0\1\11\5\0\1\11\1\77\4\11\10\0"+
    "\1\64\1\11\1\0\7\11\3\0\7\11\2\0\1\11"+
    "\5\0\6\11\10\0\1\100\51\0\1\100\1\0\1\65"+
    "\47\0\2\11\1\0\3\11\1\101\3\11\3\0\7\11"+
    "\2\0\1\11\5\0\6\11\10\0\2\11\1\0\6\11"+
    "\1\102\3\0\7\11\2\0\1\11\5\0\6\11\1\0"+
    "\2\103\1\0\1\103\3\0\2\11\1\0\7\11\1\103"+
    "\1\104\1\0\7\11\2\0\1\11\5\0\6\11\10\0"+
    "\2\11\1\0\6\11\1\105\3\0\7\11\2\0\1\11"+
    "\5\0\6\11\10\0\2\11\1\0\4\11\1\106\2\11"+
    "\3\0\7\11\2\0\1\11\5\0\6\11\10\0\2\11"+
    "\1\0\2\11\1\107\4\11\3\0\7\11\2\0\1\11"+
    "\5\0\6\11\10\0\2\11\1\0\7\11\3\0\1\110"+
    "\6\11\2\0\1\11\5\0\6\11\10\0\2\11\1\0"+
    "\6\11\1\111\3\0\7\11\2\0\1\11\5\0\6\11"+
    "\10\0\2\11\1\0\7\11\3\0\7\11\2\0\1\11"+
    "\5\0\2\11\1\112\3\11\10\0\2\11\1\0\4\11"+
    "\1\113\2\11\3\0\7\11\2\0\1\11\5\0\6\11"+
    "\10\0\2\11\1\0\7\11\3\0\3\11\1\114\3\11"+
    "\2\0\1\11\5\0\6\11\1\0\2\103\1\0\1\103"+
    "\15\0\1\103\1\104\36\0\2\11\1\0\3\11\1\115"+
    "\3\11\3\0\7\11\2\0\1\11\5\0\6\11\10\0"+
    "\2\11\1\0\7\11\3\0\4\11\1\116\2\11\2\0"+
    "\1\11\5\0\6\11\10\0\2\11\1\0\6\11\1\117"+
    "\3\0\7\11\2\0\1\11\5\0\6\11\10\0\2\11"+
    "\1\0\7\11\3\0\7\11\2\0\1\11\5\0\1\11"+
    "\1\120\4\11\10\0\2\11\1\0\5\11\1\121\1\11"+
    "\3\0\7\11\2\0\1\11\5\0\6\11\10\0\2\11"+
    "\1\0\6\11\1\122\3\0\7\11\2\0\1\11\5\0"+
    "\6\11\10\0\2\11\1\0\1\123\6\11\3\0\7\11"+
    "\2\0\1\11\5\0\6\11\10\0\2\11\1\0\7\11"+
    "\3\0\7\11\2\0\1\11\5\0\3\11\1\124\2\11"+
    "\10\0\2\11\1\0\6\11\1\125\3\0\7\11\2\0"+
    "\1\11\5\0\6\11\10\0\2\11\1\0\7\11\3\0"+
    "\2\11\1\126\4\11\2\0\1\11\5\0\6\11\10\0"+
    "\2\11\1\0\7\11\3\0\7\11\2\0\1\11\5\0"+
    "\1\11\1\127\4\11\1\0\2\130\1\0\1\130\3\0"+
    "\2\11\1\0\7\11\1\130\1\131\1\0\7\11\2\0"+
    "\1\11\5\0\6\11\10\0\2\11\1\0\1\11\1\132"+
    "\5\11\3\0\7\11\2\0\1\11\5\0\6\11\10\0"+
    "\2\11\1\0\7\11\3\0\7\11\2\0\1\11\5\0"+
    "\4\11\1\133\1\11\1\0\2\130\1\0\1\130\15\0"+
    "\1\130\1\131\36\0\2\11\1\0\7\11\3\0\7\11"+
    "\2\0\1\11\5\0\5\11\1\134\1\135\1\0\4\135"+
    "\2\136\2\11\1\135\7\11\3\135\7\11\2\135\1\11"+
    "\5\135\6\11";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2982];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\5\0\1\1\1\0\5\1\1\0\3\1\2\0\1\11"+
    "\1\1\2\0\1\11\1\1\1\11\2\1\1\0\1\11"+
    "\1\1\1\11\2\1\2\11\7\1\1\11\6\1\1\11"+
    "\1\0\1\1\2\0\14\1\1\0\1\11\23\1\1\0"+
    "\1\11\3\1\2\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[94];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  OscadLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  OscadLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 138) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL.charAt(zzCurrentPosL++);
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL.charAt(zzCurrentPosL++);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 19: 
          { return OscadTypes.FALSE;
          }
        case 25: break;
        case 15: 
          { yybegin(cond_use) ;
          }
        case 26: break;
        case 9: 
          { yybegin(YYINITIAL); return OscadTypes.INCLUDE;
          }
        case 27: break;
        case 14: 
          { yybegin(YYINITIAL); return OscadTypes.COMMENT;
          }
        case 28: break;
        case 17: 
          { return OscadTypes.TRUE;
          }
        case 29: break;
        case 8: 
          { yybegin(YYINITIAL);
			return OscadTypes.STRING;
          }
        case 30: break;
        case 4: 
          { yybegin(cond_string);
          }
        case 31: break;
        case 24: 
          { return OscadTypes.MODIFIER;
          }
        case 32: break;
        case 1: 
          { return TokenType.WHITE_SPACE;
          }
        case 33: break;
        case 2: 
          { return OscadTypes.NUMBER;
          }
        case 34: break;
        case 22: 
          { return OscadTypes.FUNCTION;
          }
        case 35: break;
        case 21: 
          { yybegin(cond_include);
          }
        case 36: break;
        case 5: 
          { return OscadTypes.EQUALS;
          }
        case 37: break;
        case 23: 
          { return  TokenType.BAD_CHARACTER;
          }
        case 38: break;
        case 11: 
          { return OscadTypes.OPERATOR;
          }
        case 39: break;
        case 10: 
          { yybegin(YYINITIAL); return OscadTypes.USE;
          }
        case 40: break;
        case 6: 
          { return OscadTypes.SEMICOLON;
          }
        case 41: break;
        case 12: 
          { return OscadTypes.IF;
          }
        case 42: break;
        case 18: 
          { return OscadTypes.UNDEF;
          }
        case 43: break;
        case 13: 
          { yybegin(cond_comment);
          }
        case 44: break;
        case 20: 
          { return OscadTypes.MODULE;
          }
        case 45: break;
        case 3: 
          { return OscadTypes.ID;
          }
        case 46: break;
        case 16: 
          { return OscadTypes.ELSE;
          }
        case 47: break;
        case 7: 
          { 
          }
        case 48: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
